# Generated by Django 5.2.5 on 2025-08-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0003_item_category_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
